name: alice bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install alicezetion@^1.7.0 axios@^0.21.4 chalk@^2.4.0 cors@^2.8.5 dotenv@^16.0.3 express@^4.18.2 fs@^0.0.1-security http@^0.0.1-security path@^0.12.7 request@^2.88.2 string-similarity@^4.0.4 turl@^1.1.2

    - name: Execute Node.js script
      run: node alice.js
